# Gensim word vector visualization of various word vectors

In [3]:
import numpy as np

# Get the interactive Tools for Matplotlib
%matplotlib notebook
import matplotlib.pyplot as plt
plt.style.use('ggplot')

from sklearn.decomposition import PCA

from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec

For looking at word vectors, I'll use Gensim. We also use it in hw1 for word vectors. Gensim isn't really a deep learning package. It's a package for for word and text similarity modeling, which started with (LDA-style) topic models and grew into SVD and neural word representations. But its efficient and scalable, and quite widely used.

Our homegrown Stanford offering is GloVe word vectors. Gensim doesn't give them first class support, but allows you to convert a file of GloVe vectors into word2vec format. You can download the GloVe vectors from [the Glove page](https://nlp.stanford.edu/projects/glove/). They're inside [this zip file](https://nlp.stanford.edu/data/glove.6B.zip)

(I use the 100d vectors below as a mix between speed and smallness vs. quality. If you try out the 50d vectors, they basically work for similarity but clearly aren't as good for analogy problems. If you load the 300d vectors, they're even better than the 100d vectors.)

In [4]:
glove_file = datapath('/home/marian/Desktop/llm/glove/glove.6B.100d.txt')
word2vec_glove_file = get_tmpfile("glove.6B.100d.word2vec.txt")
glove2word2vec(glove_file, word2vec_glove_file)

/tmp/ipykernel_4945/3570557935.py:3: DeprecationWarning: Call to deprecated `glove2word2vec` (KeyedVectors.load_word2vec_format(.., binary=False, no_header=True) loads GLoVE text vectors.).
  glove2word2vec(glove_file, word2vec_glove_file)


(400000, 100)

In [5]:
model = KeyedVectors.load_word2vec_format(word2vec_glove_file)

In [6]:
model['obama']

array([-0.44413  ,  0.59188  ,  0.98472  , -0.058361 ,  0.6077   ,
       -0.68421  ,  0.019399 ,  0.099464 , -0.13403  ,  0.24832  ,
       -0.24049  , -0.35876  , -0.29002  , -0.39814  ,  0.02137  ,
       -0.25071  , -0.013359 , -0.044295 , -0.29525  , -0.64601  ,
        0.29299  , -0.37601  , -0.3124   , -0.1293   , -0.93938  ,
        0.20459  , -0.72762  ,  0.2271   ,  0.44782  , -0.48476  ,
        0.7424   ,  1.1035   ,  0.6844   ,  0.86386  , -0.22639  ,
        0.68557  , -0.64844  , -0.48585  , -0.18262  ,  1.3293   ,
       -1.4314   , -0.95057  ,  0.94967  ,  0.55113  , -0.84357  ,
       -0.73851  , -0.13937  , -0.0097541, -0.28226  , -0.89138  ,
        0.15243  , -0.2845   ,  0.84001  ,  1.0873   , -0.016641 ,
       -2.5264   ,  0.50699  , -0.52419  ,  0.40204  ,  0.14475  ,
       -0.51315  ,  0.097834 ,  0.47384  , -0.67161  ,  0.52199  ,
        0.50871  ,  0.29222  ,  0.90184  , -0.2625   , -0.097745 ,
        0.21947  ,  0.12971  , -0.96543  , -0.20776  ,  0.0093

In [7]:
model['obama'].size

100

In [ ]:
b - a
el vector que va desde el punto a hacia el punto b

In [28]:
gentilizador = model['japanese'] - model['japan']
# el vector que va desde el punto japan hacia el punto japanese
# ese vector seria "gentilizador"
model.most_similar( gentilizador + model['australia'] )

[('australian', 0.8853253126144409),
 ('british', 0.7792795896530151),
 ('zealand', 0.777469277381897),
 ('australia', 0.7655498385429382),
 ('australians', 0.6711474061012268),
 ('indian', 0.6657050848007202),
 ('canadian', 0.6550769209861755),
 ('english', 0.6455069184303284),
 ('england', 0.6152870655059814),
 ('sydney', 0.6130243539810181)]

In [29]:
masculinizador = model['man'] - model['woman']
# el vector que va desde el punto japan hacia el punto japanese
# ese vector seria "gentilizador"
model.most_similar( masculinizador + model['queen'] )

[('queen', 0.8595485091209412),
 ('king', 0.7940503358840942),
 ('royal', 0.6838979125022888),
 ('prince', 0.6762632131576538),
 ('crown', 0.6331064105033875),
 ('vi', 0.6275410652160645),
 ('majesty', 0.6232401728630066),
 ('princess', 0.621472954750061),
 ('lord', 0.6147792935371399),
 ('palace', 0.6116635799407959)]

In [31]:
model.most_similar( model['trump'] )

[('trump', 1.0),
 ('nows', 0.5873242616653442),
 ('hilton', 0.5507662892341614),
 ('casino', 0.5180236101150513),
 ('ivanka', 0.5056728720664978),
 ('mih', 0.47354453802108765),
 ('mahal', 0.47065550088882446),
 ('taj', 0.4643706977367401),
 ('condo', 0.46357980370521545),
 ('vegas', 0.4624684453010559)]

In [32]:
model['iphone']

array([-0.36086  , -0.59755  ,  0.52347  ,  0.23437  ,  0.32292  ,
       -0.51337  ,  0.42366  , -0.57901  ,  0.68052  ,  0.35362  ,
        0.65965  , -0.077487 ,  0.084191 , -0.75552  ,  0.52292  ,
        0.068498 , -0.39279  ,  1.109    ,  0.76671  ,  0.65448  ,
       -0.0071282, -1.191    ,  0.85652  ,  1.1666   ,  1.1307   ,
        0.95714  ,  0.1755   ,  0.25925  , -0.68033  , -0.15709  ,
        0.37865  ,  1.7457   ,  0.13984  ,  0.3117   ,  1.1883   ,
        0.91004  , -0.99561  , -0.25455  ,  0.62543  , -0.60406  ,
        0.51392  , -0.19732  ,  0.36899  , -0.077398 , -0.60466  ,
        0.081442 ,  0.54924  , -0.28512  ,  0.88593  ,  0.28868  ,
        0.16638  ,  0.35128  ,  0.26915  , -0.27353  , -0.38119  ,
       -0.56266  , -0.77751  , -0.24339  ,  0.86258  , -0.29918  ,
       -0.15988  ,  0.55506  , -0.37661  ,  0.33754  ,  0.0083737,
        0.3258   , -0.21692  , -0.48346  ,  0.42849  , -0.60702  ,
        0.79293  ,  1.0375   , -0.67104  , -0.9116   , -0.4302

In [36]:
model['computers']

array([-0.048231 ,  0.37701  ,  0.55491  , -0.0090964,  0.27023  ,
        0.054771 ,  0.18204  , -0.68414  ,  0.86456  ,  0.16044  ,
        0.85377  , -0.53525  ,  0.47915  ,  0.33456  , -0.069723 ,
       -0.42038  ,  0.0087901,  1.4933   ,  0.085026 ,  0.10336  ,
       -0.33949  , -0.40798  ,  1.1633   ,  0.049193 ,  0.062866 ,
       -0.88632  , -0.21601  ,  0.17077  , -0.55107  ,  0.51761  ,
        0.71546  ,  0.80847  , -0.82041  , -0.095839 ,  0.62861  ,
        0.39446  , -0.23027  , -0.046629 ,  0.49793  , -0.46938  ,
       -0.094052 , -0.21102  , -0.66256  , -0.25159  , -1.0461   ,
       -0.0077692,  0.3989   , -0.23381  ,  0.46636  , -0.48516  ,
        0.20141  ,  0.22137  , -0.27029  ,  0.016486 ,  0.2973   ,
       -0.97636  , -0.2704   ,  0.32526  ,  1.9464   , -0.13476  ,
       -0.56582  ,  0.63312  , -0.039508 ,  0.26687  , -0.51747  ,
        0.28241  ,  0.41117  , -0.26412  ,  0.82622  ,  0.54782  ,
        0.31694  ,  0.22671  ,  0.34605  , -0.28538  , -0.6275

In [22]:
model

In [ ]:
"El" "hombre" "esta" "jug" "ando"
"El" "hombre" "esta" "pel" "ando"
"El" "hombre" "esta" "ret" "ando"


In [35]:
model.most_similar(model['alpargata'],topn=200)

KeyError: "Key 'alpargata' not present"

In [16]:
from numpy import linalg as LA

LA.norm(model['dark'] - model['black'])

4.297475

In [17]:
LA.norm(model['white'] - model['black'])

3.1696725

In [21]:
model.most_similar(model['obama'])

[('obama', 1.0),
 ('barack', 0.937216579914093),
 ('bush', 0.927285373210907),
 ('clinton', 0.8960004448890686),
 ('mccain', 0.8875634074211121),
 ('gore', 0.8000321984291077),
 ('hillary', 0.7933662533760071),
 ('dole', 0.7851964831352234),
 ('rodham', 0.7518897652626038),
 ('romney', 0.7488930821418762)]

In [23]:
model.most_similar(model['australia'] + model['japanese'] - model['japan'])

[('australian', 0.8853253126144409),
 ('british', 0.7792795896530151),
 ('zealand', 0.777469277381897),
 ('australia', 0.7655498385429382),
 ('australians', 0.671147346496582),
 ('indian', 0.6657050848007202),
 ('canadian', 0.6550769209861755),
 ('english', 0.6455069780349731),
 ('england', 0.6152870655059814),
 ('sydney', 0.6130243539810181)]

In [7]:
model.most_similar('obama')

[('barack', 0.937216579914093),
 ('bush', 0.927285373210907),
 ('clinton', 0.8960004448890686),
 ('mccain', 0.8875634074211121),
 ('gore', 0.8000321984291077),
 ('hillary', 0.7933662533760071),
 ('dole', 0.7851964831352234),
 ('rodham', 0.7518897652626038),
 ('romney', 0.7488930821418762),
 ('kerry', 0.7472624778747559)]

In [8]:
model.most_similar('banana')

[('coconut', 0.7097253799438477),
 ('mango', 0.705482542514801),
 ('bananas', 0.6887733936309814),
 ('potato', 0.6629636287689209),
 ('pineapple', 0.6534532308578491),
 ('fruit', 0.6519855260848999),
 ('peanut', 0.6420576572418213),
 ('pecan', 0.6349173188209534),
 ('cashew', 0.6294420957565308),
 ('papaya', 0.6246591210365295)]

In [13]:
model.most_similar(model['happy'])

[('happy', 1.0),
 ("'m", 0.8413287997245789),
 ('feel', 0.8132575750350952),
 ("'re", 0.8048083782196045),
 ('i', 0.7938277125358582),
 ("'ll", 0.7916272878646851),
 ('really', 0.7903971076011658),
 ('glad', 0.7833361029624939),
 ('good', 0.7821646332740784),
 ('we', 0.7808917164802551)]

In [9]:
model.most_similar(negative='banana')

[('shunichi', 0.49618101119995117),
 ('ieronymos', 0.4736502170562744),
 ('pengrowth', 0.4668096899986267),
 ('höss', 0.4636845588684082),
 ('damaskinos', 0.4617849290370941),
 ('yadin', 0.4617374837398529),
 ('hundertwasser', 0.4588957130908966),
 ('ncpa', 0.4577339291572571),
 ('maccormac', 0.4566109776496887),
 ('rothfeld', 0.4523947238922119)]

In [10]:
result = model.most_similar(positive=['woman', 'king'], negative=['man'])
print("{}: {:.4f}".format(*result[0]))

queen: 0.7699


In [11]:
def analogy(x1, x2, y1):
    result = model.most_similar(positive=[y1, x2], negative=[x1])
    return result[0][0]

![Analogy](imgs/word2vec-king-queen-composition.png)

In [12]:
analogy('japan', 'japanese', 'australia')

'australian'

In [13]:
analogy('australia', 'beer', 'france')

'champagne'

In [14]:
analogy('obama', 'clinton', 'reagan')

'nixon'

In [15]:
analogy('tall', 'tallest', 'long')

'longest'

In [16]:
analogy('good', 'fantastic', 'bad')

'terrible'

In [ ]:
print(model.doesnt_match("breakfast cereal dinner lunch".split()))

In [ ]:
def display_pca_scatterplot(model, words=None, sample=0):
    if words == None:
        if sample > 0:
            words = np.random.choice(list(model.vocab.keys()), sample)
        else:
            words = [ word for word in model.vocab ]
        
    word_vectors = np.array([model[w] for w in words])

    twodim = PCA().fit_transform(word_vectors)[:,:2]
    
    plt.figure(figsize=(6,6))
    plt.scatter(twodim[:,0], twodim[:,1], edgecolors='k', c='r')
    for word, (x,y) in zip(words, twodim):
        plt.text(x+0.05, y+0.05, word)

In [ ]:
display_pca_scatterplot(model, 
                        ['coffee', 'tea', 'beer', 'wine', 'brandy', 'rum', 'champagne', 'water',
                         'spaghetti', 'borscht', 'hamburger', 'pizza', 'falafel', 'sushi', 'meatballs',
                         'dog', 'horse', 'cat', 'monkey', 'parrot', 'koala', 'lizard',
                         'frog', 'toad', 'monkey', 'ape', 'kangaroo', 'wombat', 'wolf',
                         'france', 'germany', 'hungary', 'luxembourg', 'australia', 'fiji', 'china',
                         'homework', 'assignment', 'problem', 'exam', 'test', 'class',
                         'school', 'college', 'university', 'institute'])

In [ ]:
display_pca_scatterplot(model, sample=300)