In [2]:
import torch
import numpy as np

In [24]:
values = [[1,2,3],
          [0,1,4],
          [5,6,0]]
A = torch.tensor(values, dtype=torch.float)
A

tensor([[1., 2., 3.],
        [0., 1., 4.],
        [5., 6., 0.]])

In [12]:
A.requires_grad

False

In [18]:
A.shape

torch.Size([3, 3])

In [19]:
torch.eye(A.shape[0])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
A_inversed = torch.inverse(A)
A_inversed

tensor([[-24.0000,  18.0000,   5.0000],
        [ 20.0000, -15.0000,  -4.0000],
        [ -5.0000,   4.0000,   1.0000]], dtype=torch.float64)

In [15]:
A_inversed @ A

tensor([[ 1.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.6645e-15,  1.0000e+00, -7.1054e-15],
        [ 1.5543e-15,  2.2204e-15,  1.0000e+00]], dtype=torch.float64)

In [20]:
def distance(X,Y):
    return torch.norm(X-Y)

def distance_to_eye(X):
    return distance(X,torch.eye(X.shape[0]))

distance_to_eye(A_inversed @ A)

tensor(8.9839e-15, dtype=torch.float64)

In [25]:
W = torch.rand((3,3), requires_grad=True)
W

tensor([[0.5625, 0.3771, 0.5064],
        [0.3066, 0.1356, 0.7196],
        [0.3413, 0.8575, 0.6221]], requires_grad=True)

In [44]:
d = distance_to_eye(A @ W)
print(d)
W.grad.zero_()
d.backward()
W.grad

tensor(10.4478, grad_fn=<LinalgVectorNormBackward0>)


tensor([[2.3412, 1.6000, 3.1642],
        [3.0613, 2.4121, 4.3960],
        [0.9845, 1.9071, 2.3228]])

In [65]:
for iteration in range(30000):
    d = distance_to_eye(A @ W)
    W.grad.zero_()
    d.backward()
    W.data = W.data - 0.000005 * W.grad
    if iteration % 10000 == 0:
        print(d.item())
    

0.0012619229964911938
0.0012619229964911938
0.0012619229964911938


In [66]:
W

tensor([[-23.9696,  17.9773,   4.9938],
        [ 19.9747, -14.9811,  -3.9948],
        [ -4.9935,   3.9952,   0.9987]], requires_grad=True)

In [67]:
A_inversed

tensor([[-24.0000,  18.0000,   5.0000],
        [ 20.0000, -15.0000,  -4.0000],
        [ -5.0000,   4.0000,   1.0000]], dtype=torch.float64)